CREATE DATABASE CLASS
CREATE SCHEMA Student

CREATE TABLE Student.INFO
(FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL,
ID INT NOT NULL,
PHONE_NO INT NOT NULL
);

Select*from Student.INFO;

INSERT INTO Student.INFO
(FIRST_NAME, LAST_NAME, ID, PHONE_NO)
VALUES('SHAILJA','BHARRGAVA',1,4645),('SNEHA','RATHOR',2,4656),('SHAIL','SHARMA',3,4567),
('GANGA', 'BHARGAVA', 4, 654564)

DELETE FROM Student.INFO
WHERE ID=2

